# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7851f604cb62479d2f7634534b23342e702c7b05c310e8d94715e5e776b507d250e4047400168e560a943e35ea04e585c05ceac4a8b8dff636546d7d96fa34

test:
  secret_key_base: bbb79be86123cdc1af18dc40d6bd2544104ea64e2669d7285fa8fa7fe3927ed7e37917d30db8faa722b3fcdb64a38de9af4c5c66fe7866cb1094028846ed3b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
